CREATE TABLE TRAINEE(
TRAINEEID NUMBER,
TRAINEENAME VARCHAR2(75),
TRAINEEDOMAIN VARCHAR2(20),
TRAINEELOCATION VARCHAR2(30)
);

SELECT * FROM TRAINEE;

TRUNCATE TABLE TRAINEE;

CREATE SEQUENCE trainee_id_seq
START WITH 100
INCREMENT BY 2
NOCYCLE;